### PR TITLE
fftw lib

### PR DESCRIPTION
**Pull request by cancerberoSgx**
* I think this is an important dependency, even more than format support.
 * I took time to research and this project repository is not for users but for developers . Seems the C++ source code is currently generated from ocalm or similar technology. In my case I decided just to download the release file as they recommend. Although it has no revision information like the rest 

Also perhaps it would be a good idea to maintain the sources (as in the release file) under https://github.com/ImageMagick/fftw.git , like the rest of the dependencies ? to better control updates ? 

The build is working and now, in the output/index.html I see the new fftw delegate when loading the .wasm. Probably you want to close this PR and implement this more elegantly, probably creating a repo for the library's sources to control the versions. Also probably you need to include these changes also in build/dotnet .Feel free to close this ; the main objective of this PR was to share the recipe for a working build that I've extensively tested and know is working fine and fast in my repo, both browser and node.

### CODE REVIEW

**Comment by dlemstra** [comment]
As posted in your other issue I cannot include this because fftw uses the GPL license. I cannot do that because this project uses a license that is not compatible with the GPL license.

**Comment by cancerberoSgx** [comment]
I missed that completely thanks. I will review my project's license. Do you know of any alternative library for this ? In your case (desktop) you could perhaps enable the feature and load the library dynamically making the user responsible of installing by their own. Thanks

**Comment by dlemstra** [comment]
I am not aware of an alternative for this and combining both static and dynamic libraries is not supported by ImageMagick.

**Comment by dlemstra** [comment]
But still thanks for the PR because this could be useful for other people who can publish their project under the GPL license.

**Pull request closed without merging**
